version: "3.9"

services:
  detectron2-train:
    build:
      context: .
      args:
        CUDA_VERSION: "11.3.1"
    image: detectron2-train:latest
    container_name: detectron2-train
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NCCL_P2P_DISABLE=1
      - NCCL_IB_DISABLE=1
    volumes:
      - ./data:/data:rw
      - ./output:/output:rw
      - ./src:/workspace:rw
    working_dir: /workspace
    shm_size: "16gb"
    ports:
      - "8889:8888"
    profiles: ["train"]